import React from 'react';
import { ArrowRight, BookOpen, Check, Film, KeyRound, Music2, ShieldCheck, Sparkles, Wand2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import ShortsGallery from '../components/ShortsGallery';

const Home = () => (
  <div className="mx-auto max-w-[1440px] space-y-16 pb-10 sm:space-y-24">
    <section className="relative overflow-hidden rounded-[2rem] border border-[rgba(212,168,67,0.26)] bg-[radial-gradient(circle_at_78%_8%,rgba(212,168,67,0.18),transparent_34%),linear-gradient(135deg,var(--bg-surface),var(--bg-elevated))] px-6 py-12 sm:px-10 sm:py-16 lg:px-16 lg:py-24"><div className="absolute -right-40 -top-40 h-[34rem] w-[34rem] rounded-full border border-[rgba(242,195,91,0.12)]" aria-hidden="true" /><div className="relative grid items-end gap-12 lg:grid-cols-[1.1fr_0.9fr]"><div><p className="eyebrow">Star Lyrix Creator Studio</p><h1 className="mt-4 max-w-4xl text-5xl font-bold leading-[0.96] tracking-[-0.07em] text-[var(--text-primary)] sm:text-7xl">Turn a lyric into a world<span className="text-[var(--gold-light)]">.</span></h1><p className="mt-6 max-w-2xl text-base leading-8 text-[var(--text-secondary)] sm:text-lg">A creator-first home for original lyrics, lyric-led video ideas, and the short visual moments that make a song stay.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/auth" className="btn-primary"><Sparkles className="h-4 w-4" /> Start creating</Link><Link to="/lyrics" className="btn-secondary"><BookOpen className="h-4 w-4" /> Read the room</Link></div><p className="mt-5 text-xs text-[var(--text-muted)]">Creator tools and provider settings begin after sign in. Public pages stay focused on the work.</p></div><div className="glass-panel relative p-6 sm:p-8"><div className="flex items-center justify-between"><span className="eyebrow">The studio loop</span><Music2 className="h-5 w-5 text-[var(--gold-light)]" aria-hidden="true" /></div><div className="mt-8 space-y-5"><StudioStep number="01" title="Write" text="Shape an original lyric draft with your own AI provider." active /><StudioStep number="02" title="See" text="Build toward authorized, lyric-led video stories." /><StudioStep number="03" title="Share" text="Cut the feeling into Shorts when the rights are clear." /></div><div className="mt-8 flex items-center gap-2 border-t border-[var(--border-subtle)] pt-5 text-xs text-[var(--text-muted)]"><ShieldCheck className="h-4 w-4 text-[var(--gold-light)]" /> Original-first. Rights-aware. No autoplay.</div></div></div></section>

    <section className="grid gap-5 md:grid-cols-3" aria-label="Creator Studio principles"><Principle icon={<Wand2 className="h-5 w-5" />} title="Original lyric work" text="Bring your own AI provider into a private, focused writing flow." /><Principle icon={<Film className="h-5 w-5" />} title="Video-ready thinking" text="Move from line, to scene, to a visual story without hiding the rights work." /><Principle icon={<KeyRound className="h-5 w-5" />} title="Your keys, your control" text="Provider credentials stay behind an authenticated server boundary." /></section>

    <ShortsGallery limit={6} />

    <section className="grid items-stretch gap-6 lg:grid-cols-[0.8fr_1.2fr]"><div className="surface-card flex flex-col justify-between p-7 sm:p-9"><div><p className="eyebrow">Public reading room</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em] text-[var(--text-primary)]">For the lines that found you.</h2><p className="mt-4 text-sm leading-7 text-[var(--text-secondary)]">Search catalog identity with Spotify, then read lyrics only when an approved Musixmatch source makes them available.</p></div><Link to="/lyrics" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-[var(--gold-light)]">Open Lyrics Reader <ArrowRight className="h-4 w-4" /></Link></div><div className="relative overflow-hidden rounded-3xl border border-[rgba(212,168,67,0.22)] bg-[linear-gradient(135deg,rgba(212,168,67,0.12),transparent),var(--bg-surface)] p-7 sm:p-9"><div className="absolute right-6 top-6 flex h-12 w-12 items-center justify-center rounded-2xl border border-[rgba(242,195,91,0.3)] text-[var(--gold-light)]"><BookOpen className="h-5 w-5" /></div><p className="eyebrow">A better public boundary</p><p className="mt-8 max-w-xl font-serif text-3xl italic leading-tight text-[var(--text-primary)]">“The right words deserve the right room.”</p><div className="mt-8 grid gap-3 sm:grid-cols-2"><ReaderPromise text="Spotify catalog matching" /><ReaderPromise text="Licensed lyrics when available" /><ReaderPromise text="No scraped lyric pages" /><ReaderPromise text="Clear source language" /></div></div></section>

    <section className="relative overflow-hidden rounded-3xl border border-[var(--border-subtle)] bg-[var(--bg-surface)] p-7 sm:p-10"><div className="relative flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow">Ready when the line arrives</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em] text-[var(--text-primary)]">Make something that sounds like you.</h2><p className="mt-3 max-w-xl text-sm leading-7 text-[var(--text-secondary)]">Sign in to enter Creator Studio, connect a provider, and begin with an original lyric draft.</p></div><Link to="/auth" className="btn-primary shrink-0"><Sparkles className="h-4 w-4" /> Enter Creator Studio</Link></div></section>
  </div>
);

const StudioStep: React.FC<{ number: string; title: string; text: string; active?: boolean }> = ({ number, title, text, active }) => <div className="flex gap-4"><span className={`mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-full border font-mono text-[0.6rem] ${active ? 'border-[rgba(242,195,91,0.5)] bg-[rgba(212,168,67,0.14)] text-[var(--gold-light)]' : 'border-[var(--border-subtle)] text-[var(--text-muted)]'}`}>{number}</span><div><h2 className="font-semibold text-[var(--text-primary)]">{title}</h2><p className="mt-1 text-sm leading-6 text-[var(--text-secondary)]">{text}</p></div></div>;

const Principle: React.FC<{ icon: React.ReactNode; title: string; text: string }> = ({ icon, title, text }) => <article className="surface-card p-6"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[rgba(212,168,67,0.12)] text-[var(--gold-light)]">{icon}</span><h2 className="mt-5 text-lg font-semibold text-[var(--text-primary)]">{title}</h2><p className="mt-2 text-sm leading-6 text-[var(--text-secondary)]">{text}</p></article>;

const ReaderPromise: React.FC<{ text: string }> = ({ text }) => <div className="flex items-center gap-2 text-sm text-[var(--text-secondary)]"><Check className="h-4 w-4 text-[var(--gold-light)]" />{text}</div>;

export default Home;
